"""
Django settings for stepchengeru project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/


# Application definition

SITE_ID = 1

ROOT_URLCONF = 'stepchengeru.urls'

WSGI_APPLICATION = 'stepchengeru.wsgi.application'



