# Generated by Django 3.0.3 on 2020-02-27 10:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200227_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
    ]
