# Generated by Django 3.0.3 on 2020-03-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200310_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_button',
            new_name='banner_button_page',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button_url',
            field=models.URLField(default='/login/', null=True),
        ),
    ]
