# Generated by Django 3.0.3 on 2020-03-13 13:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0012_auto_20200311_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('banner_title', models.CharField(max_length=100, null=True)),
                ('banner_subtitle', models.CharField(default='', max_length=250)),
                ('banner_button_text', models.CharField(blank=True, max_length=250, null=True)),
                ('banner_button_url', models.URLField(default='/login/', null=True)),
                ('banner_button_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('banner_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_button_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_button_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title',
        ),
        migrations.DeleteModel(
            name='HomePageCarouselImages',
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='home.HomePage'),
        ),
    ]
