# Generated by Django 3.0.3 on 2020-03-13 14:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0013_auto_20200313_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebanner',
            name='banner_button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='banner_button_url',
            field=models.CharField(blank=True, default='/login/', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='banner_subtitle',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_banner', to='home.HomePage'),
        ),
    ]
