# Generated by Django 3.0.4 on 2020-03-14 16:36

from django.db import migrations
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200313_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, max_length=100, null=True)), ('subtitle', wagtail.core.blocks.CharBlock(blank=True, default='', max_length=250, null=True)), ('image', wagtail.images.blocks.ImageChooserBlock(wagtail.images.models.Image, blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+')), ('button_text', wagtail.core.blocks.CharBlock(blank=True, max_length=250, null=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.CharBlock(required=False))])), ('cta', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image from call to action. If need.', required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('text', wagtail.core.blocks.RichTextBlock(required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Узнать больше', max_length=40, required=True))])), ('row', wagtail.core.blocks.StructBlock([('width', wagtail.core.blocks.ChoiceBlock(choices=[('default', 'Default'), ('full', 'Full')])), ('content', wagtail.core.blocks.StreamBlock([('p', streams.blocks.RichtextBlock()), ('alert', wagtail.core.blocks.StructBlock([('css_class', wagtail.core.blocks.ChoiceBlock(choices=[('info', 'Info'), ('error', 'Error')], help_text='Цвет подложки и значёк')), ('title', wagtail.core.blocks.CharBlock(help_text='Верхний, жирный текст', max_length=250)), ('text', streams.blocks.RichtextBlock())])), ('card', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='', required=False))])))])), ('cta', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image from call to action. If need.', required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('text', wagtail.core.blocks.RichTextBlock(required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Узнать больше', max_length=40, required=True))]))]))]))], blank=True, null=True),
        ),
    ]
