# Generated by Django 3.0.3 on 2020-03-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, help_text='facebook URL', max_length=1023, null=True)),
                ('twitter', models.CharField(blank=True, help_text='twitter URL', max_length=1023, null=True)),
                ('vkontakte', models.CharField(blank=True, help_text='vkontakte URL', max_length=1023, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
