# Generated by Django 3.0.3 on 2020-03-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='facebook URL', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='twitter URL', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='vkontakte',
            field=models.URLField(blank=True, help_text='vkontakte URL', max_length=1023, null=True),
        ),
    ]
